# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: TaisTalecraft
email: taisiia.narrative@gmail.com
url: https://taistalecraft.com
description: >- # this means to ignore newlines until "baseurl:"
  Taisiia Smirnova - I’m a narrative designer and game screenwriter and I love it ❤️
twitter_username: username
github_username: sunflowergolem
minimal_mistakes_skin: default
search: true
teaser: /assets/images/500x300.png
logo: /assets/images/logo.png
masthead_title: " "

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: G-B14W04NZW0

author:
  name: "Taisiia Smirnova"
  avatar: "/assets/images/avatar.png"
  bio: "I’m a narrative designer and game screenwriter and I love it ❤️"
  location: "Houston, TX"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:taisiia.narrative@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/taisiia-smirnova-narrative/"
    - label: "CV / Resume"
      icon: "fas fa-fw fa-file"
      url: "/assets/Taisiia Smirnova - Game Writer and Narrative Designer - CV.pdf"
    - label: "Hire Me"
      icon: "fas fa-fw fa-link"
      url: "/hire-me"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:taisiia.narrative@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/taisiia-smirnova-narrative/"
    - label: "CV / Resume"
      icon: "fas fa-fw fa-file"
      url: "/assets/Taisiia Smirnova - Game Writer and Narrative Designer - CV.pdf"
    - label: "Hire Me"
      icon: "fas fa-fw fa-link"
      url: "/hire-me"

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      classes: wide
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
      classes: wide

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
